// AUTO-GENERATED by firepact. DO NOT EDIT.
// Source of truth: Pydantic models -> Firestore document contract.

import { DocumentReference, FieldValue, Timestamp } from "firebase/firestore";

// @firestore-collection rooms/{roomId}/messages
export interface Message {
  author?: DocumentReference<Profile>;
  authorProfile?: Profile;
  body: string;
  createdAt?: Timestamp | null;
  id: string;
  metadata?: Record<string, string>;
  reactions?: Reaction[];
  tags?: string[];
}

export interface MessageWrite {
  author: DocumentReference<Profile>;
  authorProfile: ProfileWrite;
  body: string;
  createdAt: FieldValue;
  metadata: Record<string, string>;
  reactions: ReactionWrite[];
  tags: string[];
}

export interface Profile {
  avatarUrl?: string | null;
  displayName?: string;
}

export interface ProfileWrite {
  avatarUrl: string | null;
  displayName: string;
}

export interface Reaction {
  count?: number;
  emoji?: string;
}

export interface ReactionWrite {
  count: number;
  emoji: string;
}

