// AUTO-GENERATED by firepact. DO NOT EDIT.
// Source of truth: Pydantic models -> Firestore document contract.

import { DocumentReference, FieldValue, FirestoreDataConverter, Timestamp } from "firebase/firestore";

// @firestore-collection rooms/{roomId}/messages
export interface Message {
  author?: DocumentReference<Profile>;
  authorProfile?: Profile;
  body: string;
  createdAt?: Timestamp | null;
  id: string;
  kind?: MessageKind | (string & {});
  metadata?: Record<string, string>;
  reactions?: Reaction[];
  tags?: string[];
}

export interface MessageWrite {
  author: DocumentReference<Profile>;
  authorProfile: ProfileWrite;
  body: string;
  createdAt: FieldValue;
  kind: MessageKind;
  metadata: Record<string, string>;
  reactions: ReactionWrite[];
  tags: string[];
}

export type MessageKind = "text" | "image" | "system";

export interface Profile {
  avatarUrl?: string | null;
  displayName?: string;
}

export interface ProfileWrite {
  avatarUrl: string | null;
  displayName: string;
}

export interface Reaction {
  count?: number;
  emoji?: string;
}

export interface ReactionWrite {
  count: number;
  emoji: string;
}

export const messageConverter: FirestoreDataConverter<Message, MessageWrite> = {
  toFirestore: (model) => model,
  fromFirestore: (snapshot, options) => {
    const data = snapshot.data(options) as Omit<Message, "id">;
    return { ...data, id: snapshot.id };
  },
};

