// AUTO-GENERATED by firepact. DO NOT EDIT.
// Source of truth: Pydantic models -> Firestore document contract.

import type { Bytes, DocumentReference, FieldValue, FirestoreDataConverter, GeoPoint, Timestamp, UpdateData } from "firebase/firestore";

export interface FileAttachment {
  kind?: "file";
  size?: number;
  url?: string;
}

export interface FileAttachmentWrite {
  kind: "file";
  size: number;
  url: string;
}

export interface ImageAttachment {
  kind?: "image";
  url?: string;
  width?: number;
}

export interface ImageAttachmentWrite {
  kind: "image";
  url: string;
  width: number;
}

// @firestore-collection rooms/{roomId}/messages
export interface Message {
  attachment?: ImageAttachment | FileAttachment;
  author?: DocumentReference<Profile>;
  authorProfile?: Profile;
  body: string;
  createdAt?: Timestamp | null;
  editedAt?: Timestamp;
  id: string;
  kind?: MessageKind | (string & {});
  location?: GeoPoint;
  metadata?: Record<string, string>;
  pinned?: boolean;
  priority?: number;
  reactions?: Reaction[];
  selection?: [number, number];
  tags?: string[];
  thumbnail?: Bytes;
}

export interface MessageWrite {
  attachment: ImageAttachmentWrite | FileAttachmentWrite;
  author: DocumentReference<Profile>;
  authorProfile: ProfileWrite;
  body: string;
  createdAt: FieldValue;
  editedAt: Timestamp | Date;
  kind: MessageKind;
  location: GeoPoint;
  metadata: Record<string, string>;
  pinned: boolean;
  priority: number;
  reactions: ReactionWrite[];
  selection: [number, number];
  tags: string[];
  thumbnail: Bytes;
}

export type MessageUpdate = UpdateData<MessageWrite>;

export type MessageKind = "text" | "image" | "system";

export interface Profile {
  avatarUrl?: string | null;
  displayName?: string;
}

export interface ProfileWrite {
  avatarUrl: string | null;
  displayName: string;
}

export interface Reaction {
  count?: number;
  emoji?: string;
}

export interface ReactionWrite {
  count: number;
  emoji: string;
}

// Read converter (onSnapshot / getDoc): injects the doc id. For writes
// use `MessageWrite` with setDoc/updateDoc directly (not via this converter).
export const messageConverter: FirestoreDataConverter<Message> = {
  toFirestore: (model) => {
    const { id: _id, ...rest } = model;
    return rest;
  },
  fromFirestore: (snapshot, options) => {
    const data = snapshot.data(options) as Omit<Message, "id">;
    return { ...data, id: snapshot.id };
  },
};

export const messagesPath = (roomId: string) => `rooms/${roomId}/messages`;

