// AUTO-GENERATED by firepact. DO NOT EDIT.
// Source of truth: Pydantic models -> Firestore document contract.

import type { FirestoreDataConverter, Timestamp, UpdateData } from "firebase/firestore";

import type { ChatStatus, MessageRole } from "./dtos";

// @firestore-collection users/{userId}/chats
export interface Chat {
  created_at: Timestamp;
  id: string;
  messages: ChatMessage[];
  status: ChatStatus | (string & {});
  updated_at: Timestamp;
  version: number;
}

export interface ChatWrite {
  created_at: Timestamp | Date;
  id: string;
  messages: ChatMessageWrite[];
  status: ChatStatus;
  updated_at: Timestamp | Date;
  version: number;
}

export type ChatUpdate = UpdateData<ChatWrite>;

export interface ChatMessage {
  created_at?: Timestamp;
  id?: string;
  role?: MessageRole | (string & {});
  text?: string;
}

export interface ChatMessageWrite {
  created_at: Timestamp | Date;
  id: string;
  role: MessageRole;
  text: string;
}

// @firestore-collection users
export interface User {
  created_at: Timestamp;
  display_name?: string | null;
  handle: string;
  id: string;
  plan?: string;
  updated_at: Timestamp;
  version: number;
}

export interface UserWrite {
  created_at: Timestamp | Date;
  display_name?: string | null;
  handle: string;
  id: string;
  plan: string;
  updated_at: Timestamp | Date;
  version: number;
}

export type UserUpdate = UpdateData<UserWrite>;

// Read converter (onSnapshot / getDoc): injects the doc id. For writes
// use `ChatWrite` with setDoc/updateDoc directly (not via this converter).
export const chatConverter: FirestoreDataConverter<Chat> = {
  toFirestore: (model) => {
    return model;
  },
  fromFirestore: (snapshot, options) => {
    return snapshot.data(options) as Chat;
  },
};

export const chatsPath = (userId: string) => `users/${userId}/chats`;

// Read converter (onSnapshot / getDoc): injects the doc id. For writes
// use `UserWrite` with setDoc/updateDoc directly (not via this converter).
export const userConverter: FirestoreDataConverter<User> = {
  toFirestore: (model) => {
    return model;
  },
  fromFirestore: (snapshot, options) => {
    return snapshot.data(options) as User;
  },
};

export const usersPath = () => `users`;

