//! firepact-core: convert a Firestore-annotated JSON Schema bundle ($defs)
//! into read/write view TypeScript. Pure, no Python, no Node.

use serde_json::{Map, Value};
use std::collections::BTreeSet;

pub mod compat;

#[derive(Clone, Copy, PartialEq, Eq)]
pub enum View {
    Read,
    Write,
}

struct Ctx<'a> {
    defs: &'a Map<String, Value>,
    /// firebase/firestore symbols actually used (for the import line).
    used: BTreeSet<&'static str>,
}

/// Entry point. `bundle` is the object returned by models_json_schema (has "$defs").
pub fn emit(bundle: &Value) -> String {
    let empty = Map::new();
    let defs = bundle
        .get("$defs")
        .and_then(Value::as_object)
        .unwrap_or(&empty);

    let mut ctx = Ctx {
        defs,
        used: BTreeSet::new(),
    };

    let mut body = String::new();
    let mut converters = String::new();
    // deterministic order: $defs is a sorted map -> stable output for diffing.
    for (name, node) in defs.iter() {
        if node.get("enum").is_some() {
            body.push_str(&render_enum(name, node));
        } else if is_object(node) {
            body.push_str(&ctx.render_interface(name, node, View::Read));
            body.push_str(&ctx.render_interface(name, node, View::Write));
            // Realtime roots get a minimal converter so the read-view doc-id
            // contract (`id: snapshot.id`) is actually satisfiable.
            if node.get("x-firestore-collection").is_some() {
                converters.push_str(&ctx.render_converter(name, node));
            }
        }
        // (scalars / unsupported top-level nodes are skipped)
    }
    body.push_str(&converters);

    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by firepact. DO NOT EDIT.\n");
    out.push_str("// Source of truth: Pydantic models -> Firestore document contract.\n\n");
    if !ctx.used.is_empty() {
        let syms: Vec<&str> = ctx.used.iter().copied().collect();
        out.push_str(&format!(
            "import {{ {} }} from \"firebase/firestore\";\n\n",
            syms.join(", ")
        ));
    }
    out.push_str(&body);
    out
}

fn is_object(node: &Value) -> bool {
    node.get("properties").is_some() || node.get("type").and_then(Value::as_str) == Some("object")
}

fn render_enum(name: &str, node: &Value) -> String {
    let variants: Vec<String> = node
        .get("enum")
        .and_then(Value::as_array)
        .map(|a| a.iter().map(literal).collect())
        .unwrap_or_default();
    // NOTE: read-side open-enum ( | (string & {}) ) is trap #5, layered on later.
    format!(
        "export type {} = {};\n\n",
        name,
        if variants.is_empty() {
            "never".to_string()
        } else {
            variants.join(" | ")
        }
    )
}

impl<'a> Ctx<'a> {
    fn render_interface(&mut self, name: &str, node: &Value, view: View) -> String {
        let ty_name = match view {
            View::Read => name.to_string(),
            View::Write => format!("{name}Write"),
        };

        let required: BTreeSet<&str> = node
            .get("required")
            .and_then(Value::as_array)
            .map(|a| a.iter().filter_map(Value::as_str).collect())
            .unwrap_or_default();

        let doc_id = node.get("x-firestore-doc-id-field").and_then(Value::as_str);

        let mut lines = String::new();
        let empty = Map::new();
        let props = node
            .get("properties")
            .and_then(Value::as_object)
            .unwrap_or(&empty);

        for (key, prop) in props.iter() {
            // Document ID: it is the key, not part of data().
            if Some(key.as_str()) == doc_id {
                match view {
                    // converter injects snapshot.id -> always present, string.
                    View::Read => {
                        lines.push_str(&format!("  {}: string;\n", ident(key)));
                    }
                    // excluded from the create payload (it is the doc path).
                    View::Write => {}
                }
                continue;
            }

            let ty = self.render_type(prop, view);
            let optional = self.is_optional(key, prop, view, &required);
            let q = if optional { "?" } else { "" };
            lines.push_str(&format!("  {}{}: {};\n", ident(key), q, ty));
        }

        let mut head = String::new();
        if view == View::Read {
            if let Some(col) = node.get("x-firestore-collection").and_then(Value::as_str) {
                head.push_str(&format!("// @firestore-collection {col}\n"));
            }
        }
        format!("{head}export interface {ty_name} {{\n{lines}}}\n\n")
    }

    /// A minimal converter for a realtime root: round-trips the write payload and
    /// injects the document id on read (so the read view's `id: string` holds).
    /// The richer converter (typed path helpers) is layered on in Phase 2.
    fn render_converter(&mut self, name: &str, node: &Value) -> String {
        self.used.insert("FirestoreDataConverter");
        let const_name = lower_first(name);
        let read = name;
        // A single app-type converter (the read view). Read/write asymmetry is
        // expressed by the separate `{name}Write` type used for write payloads;
        // forcing it as the converter's DbModelType cannot type-check because a
        // read value (e.g. `Timestamp | null`) is not a write value (`FieldValue`).
        let from_body = match node.get("x-firestore-doc-id-field").and_then(Value::as_str) {
            Some(doc_id) => format!(
                "    const data = snapshot.data(options) as Omit<{read}, \"{doc_id}\">;\n    return {{ ...data, {doc_id}: snapshot.id }};\n",
            ),
            None => format!("    return snapshot.data(options) as {read};\n"),
        };
        format!(
            "export const {const_name}Converter: FirestoreDataConverter<{read}> = {{\n\
             \x20 toFirestore: (model) => model,\n\
             \x20 fromFirestore: (snapshot, options) => {{\n\
             {from_body}\
             \x20 }},\n\
             }};\n\n"
        )
    }

    /// Optionality (`?`) is orthogonal to value-nullability.
    fn is_optional(&self, key: &str, prop: &Value, view: View, required: &BTreeSet<&str>) -> bool {
        match view {
            // write = "what must I provide to create a valid doc" = Pydantic required.
            View::Write => !required.contains(key),
            // read: required ONLY if presence is guaranteed across live docs.
            View::Read => read_optional(prop, required, key),
        }
    }

    fn render_type(&mut self, node: &Value, view: View) -> String {
        // 1) Firestore native types override the JSON shape.
        if let Some(fs) = node.get("x-firestore-type").and_then(Value::as_str) {
            return self.render_firestore(fs, node, view);
        }
        // 2) $ref -> named type (per-view name for objects).
        if let Some(r) = node.get("$ref").and_then(Value::as_str) {
            return self.render_ref(r, view);
        }
        // 3) const literal.
        if let Some(c) = node.get("const") {
            return literal(c);
        }
        // 4) inline enum. String enums read as an open union (trap #5).
        if let Some(arr) = node.get("enum").and_then(Value::as_array) {
            let strict = arr.iter().map(literal).collect::<Vec<_>>().join(" | ");
            if view == View::Read && arr.iter().all(Value::is_string) {
                return format!("{strict}{OPEN_ENUM_SUFFIX}");
            }
            return strict;
        }
        // 5) anyOf / oneOf -> union (null branch -> "null").
        for k in ["anyOf", "oneOf"] {
            if let Some(arr) = node.get(k).and_then(Value::as_array) {
                let parts: Vec<String> = arr.iter().map(|b| self.render_type(b, view)).collect();
                return dedup_union(parts);
            }
        }
        // 6) by JSON "type" (string or array of strings).
        match node.get("type") {
            Some(Value::String(t)) => self.render_json_type(t, node, view),
            Some(Value::Array(types)) => {
                let parts: Vec<String> = types
                    .iter()
                    .filter_map(Value::as_str)
                    .map(|t| self.render_json_type(t, node, view))
                    .collect();
                dedup_union(parts)
            }
            _ => "unknown".to_string(),
        }
    }

    fn render_firestore(&mut self, fs: &str, node: &Value, view: View) -> String {
        match fs {
            "timestamp" => {
                let server = node
                    .get("x-firestore-server-timestamp")
                    .and_then(Value::as_bool)
                    .unwrap_or(false);
                match (view, server) {
                    (View::Read, true) => {
                        self.used.insert("Timestamp");
                        "Timestamp | null".to_string()
                    }
                    (View::Read, false) => {
                        self.used.insert("Timestamp");
                        "Timestamp".to_string()
                    }
                    (View::Write, true) => {
                        self.used.insert("FieldValue");
                        "FieldValue".to_string()
                    }
                    (View::Write, false) => {
                        self.used.insert("Timestamp");
                        "Timestamp | Date".to_string()
                    }
                }
            }
            "bytes" => "Uint8Array".to_string(), // global, no import
            "geopoint" => {
                self.used.insert("GeoPoint");
                "GeoPoint".to_string()
            }
            "reference" => {
                self.used.insert("DocumentReference");
                // a reference always points to the canonical (read) stored shape.
                match node.get("x-firestore-ref-target").and_then(Value::as_str) {
                    Some(t) => format!("DocumentReference<{}>", t),
                    None => {
                        self.used.insert("DocumentData");
                        "DocumentReference<DocumentData>".to_string()
                    }
                }
            }
            _ => "unknown".to_string(),
        }
    }

    fn render_ref(&self, r: &str, view: View) -> String {
        let name = r.rsplit('/').next().unwrap_or(r);
        let def = self.defs.get(name);
        let is_enum = def.map(|d| d.get("enum").is_some()).unwrap_or(false);
        if is_enum {
            // The enum def is emitted once, view-agnostic (no Write suffix).
            // Openness (trap #5) is applied at the read reference site only,
            // and only for string enums (no clean open idiom for numbers).
            let string_enum = def.map(is_string_enum_node).unwrap_or(false);
            if view == View::Read && string_enum {
                format!("{name}{OPEN_ENUM_SUFFIX}")
            } else {
                name.to_string()
            }
        } else {
            match view {
                View::Read => name.to_string(),
                View::Write => format!("{name}Write"),
            }
        }
    }

    fn render_json_type(&mut self, t: &str, node: &Value, view: View) -> String {
        match t {
            "string" => "string".to_string(),
            "integer" | "number" => "number".to_string(),
            "boolean" => "boolean".to_string(),
            "null" => "null".to_string(),
            "array" => {
                if let Some(items) = node.get("items") {
                    let inner = self.render_type(items, view);
                    if inner.contains('|') {
                        format!("({inner})[]")
                    } else {
                        format!("{inner}[]")
                    }
                } else {
                    "unknown[]".to_string()
                }
            }
            "object" => {
                // dict[str, T] -> Record<string, T>
                match node.get("additionalProperties") {
                    Some(Value::Object(_)) => {
                        let inner =
                            self.render_type(node.get("additionalProperties").unwrap(), view);
                        format!("Record<string, {inner}>")
                    }
                    Some(Value::Bool(true)) | None => "Record<string, unknown>".to_string(),
                    _ => "Record<string, never>".to_string(),
                }
            }
            _ => "unknown".to_string(),
        }
    }
}

/// Read-side open-enum tail: lets a string union accept unknown members so a
/// backend adding/removing enum values never breaks an old front (trap #5).
const OPEN_ENUM_SUFFIX: &str = " | (string & {})";

/// Whether a field is optional in the read view: required ONLY when presence is
/// guaranteed across all live docs (`required` ∩ presence-guaranteed). Shared by
/// the emitter and the compat gate so the two never drift.
pub fn read_optional(prop: &Value, required: &BTreeSet<&str>, key: &str) -> bool {
    let guaranteed = prop
        .get("x-firestore-presence-guaranteed")
        .and_then(Value::as_bool)
        .unwrap_or(false);
    !(required.contains(key) && guaranteed)
}

/// The read-view TypeScript type of a single field, used as the compat signature.
/// `defs` is the bundle's `$defs` (needed to resolve `$ref` enum string-ness).
pub fn read_type_signature(defs: &Map<String, Value>, prop: &Value) -> String {
    let mut ctx = Ctx {
        defs,
        used: BTreeSet::new(),
    };
    ctx.render_type(prop, View::Read)
}

/// Lowercase the first character (PascalCase type -> camelCase value name).
fn lower_first(name: &str) -> String {
    let mut chars = name.chars();
    match chars.next() {
        Some(c) => c.to_lowercase().chain(chars).collect(),
        None => String::new(),
    }
}

/// True when the node is an enum whose every member is a string literal.
fn is_string_enum_node(node: &Value) -> bool {
    node.get("enum")
        .and_then(Value::as_array)
        .map(|a| !a.is_empty() && a.iter().all(Value::is_string))
        .unwrap_or(false)
}

fn dedup_union(parts: Vec<String>) -> String {
    let mut seen = BTreeSet::new();
    let mut ordered = Vec::new();
    for p in parts {
        if seen.insert(p.clone()) {
            ordered.push(p);
        }
    }
    ordered.join(" | ")
}

fn literal(v: &Value) -> String {
    match v {
        Value::String(s) => format!("\"{}\"", s.replace('"', "\\\"")),
        Value::Bool(b) => b.to_string(),
        Value::Number(n) => n.to_string(),
        Value::Null => "null".to_string(),
        _ => "unknown".to_string(),
    }
}

fn ident(key: &str) -> String {
    let valid = !key.is_empty()
        && key
            .chars()
            .next()
            .map(|c| c.is_ascii_alphabetic() || c == '_' || c == '$')
            .unwrap_or(false)
        && key
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$');
    if valid {
        key.to_string()
    } else {
        format!("\"{}\"", key.replace('"', "\\\""))
    }
}

/// PyO3 bindings (compiled only for the maturin extension build). Lets the
/// Python layer call the emitter natively instead of shelling out to the binary.
#[cfg(feature = "python")]
mod python {
    use pyo3::exceptions::PyValueError;
    use pyo3::prelude::*;

    /// Emit read/write TypeScript from a contract bundle given as a JSON string.
    #[pyfunction]
    fn emit(bundle_json: &str) -> PyResult<String> {
        let bundle: serde_json::Value =
            serde_json::from_str(bundle_json).map_err(|e| PyValueError::new_err(e.to_string()))?;
        Ok(crate::emit(&bundle))
    }

    #[pymodule]
    fn _core(m: &Bound<'_, PyModule>) -> PyResult<()> {
        m.add_function(wrap_pyfunction!(emit, m)?)?;
        Ok(())
    }
}
