//! firepact-core: convert a Firestore-annotated JSON Schema bundle ($defs)
//! into read/write view TypeScript. Pure, no Python, no Node.

use serde_json::{Map, Value};
use std::collections::BTreeSet;

pub mod compat;

#[derive(Clone, Copy, PartialEq, Eq)]
pub enum View {
    Read,
    Write,
}

struct Ctx<'a> {
    defs: &'a Map<String, Value>,
    /// firebase/firestore symbols actually used (for the import line).
    used: BTreeSet<&'static str>,
    /// When set, render a structural *compat signature* instead of emit output:
    /// string enums collapse to `string` (open unions accept any string), and
    /// numeric enums inline their members (member changes must stay visible).
    compat: bool,
    /// Plain (non-Firestore DTO) mode: a single interface per model with declared
    /// optionality, strict enums (no open union), no read/write split, no
    /// converter/path helper. Used by `emit_plain` to replace the legacy
    /// pydantic2ts plain output (datetime -> string, etc.).
    plain: bool,
    /// `$def` names to IMPORT from another module instead of defining here
    /// (cross-file single source); referenced ones become a type-only import.
    shared: BTreeSet<String>,
    /// Of `shared`, the names actually referenced by the output (-> import line).
    shared_used: BTreeSet<String>,
}

/// Entry point. `bundle` is the object returned by models_json_schema (has "$defs").
pub fn emit(bundle: &Value) -> String {
    emit_inner(bundle, BTreeSet::new(), "")
}

/// Like [`emit`], but the named `$defs` are IMPORTED from `shared_path` (a TS
/// module specifier relative to the output file) instead of being defined here.
/// Used for cross-file single-sourcing of shared types (e.g. enums that also live
/// in a plain DTO module). Names not referenced by the output are not imported.
pub fn emit_shared(bundle: &Value, shared_path: &str, shared_names: &[String]) -> String {
    emit_inner(bundle, shared_names.iter().cloned().collect(), shared_path)
}

fn emit_inner(bundle: &Value, shared: BTreeSet<String>, shared_path: &str) -> String {
    let empty = Map::new();
    let defs = bundle
        .get("$defs")
        .and_then(Value::as_object)
        .unwrap_or(&empty);

    let mut ctx = Ctx {
        defs,
        used: BTreeSet::new(),
        compat: false,
        plain: false,
        shared,
        shared_used: BTreeSet::new(),
    };

    let mut body = String::new();
    let mut converters = String::new();
    // deterministic order: $defs is a sorted map -> stable output for diffing.
    for (name, node) in defs.iter() {
        // Shared types are imported, not redefined.
        if ctx.shared.contains(name.as_str()) {
            continue;
        }
        if node.get("enum").is_some() {
            body.push_str(&render_enum(name, node));
        } else if is_object(node) {
            body.push_str(&ctx.render_interface(name, node, View::Read));
            body.push_str(&ctx.render_interface(name, node, View::Write));
            // Realtime roots get the update view, a converter, and a typed path
            // helper (the doc-id converter keeps `id: snapshot.id` satisfiable).
            if let Some(col) = node.get("x-firestore-collection").and_then(Value::as_str) {
                // Complete update view: optional fields + FieldValue + nested
                // paths, via firebase's own UpdateData<T> (DESIGN S5.4).
                ctx.used.insert("UpdateData");
                body.push_str(&format!(
                    "export type {name}Update = UpdateData<{name}Write>;\n\n"
                ));
                converters.push_str(&ctx.render_converter(name, node));
                converters.push_str(&render_path_helper(col));
            }
        }
        // (scalars / unsupported top-level nodes are skipped)
    }
    body.push_str(&converters);

    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by firepact. DO NOT EDIT.\n");
    out.push_str("// Source of truth: Pydantic models -> Firestore document contract.\n\n");
    if !ctx.used.is_empty() {
        // All firebase/firestore symbols we reference appear only in type
        // positions, so emit a type-only import -- valid under verbatimModuleSyntax
        // / isolatedModules (the modern strict default in TS 6/7 toolchains).
        let syms: Vec<&str> = ctx.used.iter().copied().collect();
        out.push_str(&format!(
            "import type {{ {} }} from \"firebase/firestore\";\n\n",
            syms.join(", ")
        ));
    }
    // Cross-file shared types imported from the sibling module.
    if !ctx.shared_used.is_empty() {
        let names: Vec<&str> = ctx.shared_used.iter().map(String::as_str).collect();
        out.push_str(&format!(
            "import type {{ {} }} from \"{}\";\n\n",
            names.join(", "),
            shared_path
        ));
    }
    out.push_str(&body);
    out
}

/// Plain mode: emit standard Pydantic -> TypeScript for non-Firestore DTOs --
/// one interface per model with declared optionality, strict enums, and
/// `datetime` -> `string` (the bundle carries no `x-firestore-*`). This replaces
/// the legacy pydantic2ts + external json2ts plain output.
pub fn emit_plain(bundle: &Value) -> String {
    let empty = Map::new();
    let defs = bundle
        .get("$defs")
        .and_then(Value::as_object)
        .unwrap_or(&empty);
    let mut ctx = Ctx {
        defs,
        used: BTreeSet::new(),
        compat: false,
        plain: true,
        shared: BTreeSet::new(),
        shared_used: BTreeSet::new(),
    };
    let mut body = String::new();
    for (name, node) in defs.iter() {
        if node.get("enum").is_some() {
            body.push_str(&render_enum(name, node));
        } else if is_object(node) {
            body.push_str(&ctx.render_plain_interface(name, node));
        }
    }
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by firepact (plain mode). DO NOT EDIT.\n");
    out.push_str("// Source of truth: Pydantic models (plain DTOs).\n\n");
    out.push_str(&body);
    out
}

fn is_object(node: &Value) -> bool {
    node.get("properties").is_some() || node.get("type").and_then(Value::as_str) == Some("object")
}

fn render_enum(name: &str, node: &Value) -> String {
    let variants: Vec<String> = node
        .get("enum")
        .and_then(Value::as_array)
        .map(|a| a.iter().map(literal).collect())
        .unwrap_or_default();
    // NOTE: read-side open-enum ( | (string & {}) ) is trap #5, layered on later.
    format!(
        "export type {} = {};\n\n",
        name,
        if variants.is_empty() {
            "never".to_string()
        } else {
            variants.join(" | ")
        }
    )
}

impl<'a> Ctx<'a> {
    fn render_interface(&mut self, name: &str, node: &Value, view: View) -> String {
        let ty_name = match view {
            View::Read => name.to_string(),
            View::Write => format!("{name}Write"),
        };

        let required: BTreeSet<&str> = node
            .get("required")
            .and_then(Value::as_array)
            .map(|a| a.iter().filter_map(Value::as_str).collect())
            .unwrap_or_default();

        let doc_id = node.get("x-firestore-doc-id-field").and_then(Value::as_str);

        let mut lines = String::new();
        let empty = Map::new();
        let props = node
            .get("properties")
            .and_then(Value::as_object)
            .unwrap_or(&empty);

        for (key, prop) in props.iter() {
            // Document ID: it is the key, not part of data().
            if Some(key.as_str()) == doc_id {
                match view {
                    // converter injects snapshot.id -> always present, string.
                    View::Read => {
                        lines.push_str(&format!("  {}: string;\n", ident(key)));
                    }
                    // excluded from the create payload (it is the doc path).
                    View::Write => {}
                }
                continue;
            }

            // readOnly fields (e.g. Pydantic @computed_field) are derived on the
            // backend, not provided by the writer: present on read, excluded from
            // the write view (OpenAPI readOnly semantics).
            if view == View::Write && prop.get("readOnly").and_then(Value::as_bool) == Some(true) {
                continue;
            }

            let ty = self.render_type(prop, view);
            let optional = self.is_optional(key, prop, view, &required);
            let q = if optional { "?" } else { "" };
            lines.push_str(&format!("  {}{}: {};\n", ident(key), q, ty));
        }

        let mut head = String::new();
        if view == View::Read {
            if let Some(col) = node.get("x-firestore-collection").and_then(Value::as_str) {
                head.push_str(&format!("// @firestore-collection {col}\n"));
            }
        }
        format!("{head}export interface {ty_name} {{\n{lines}}}\n\n")
    }

    /// A single plain interface (no read/write split, declared optionality). Used
    /// by `emit_plain` for non-Firestore DTOs.
    fn render_plain_interface(&mut self, name: &str, node: &Value) -> String {
        let required: BTreeSet<&str> = node
            .get("required")
            .and_then(Value::as_array)
            .map(|a| a.iter().filter_map(Value::as_str).collect())
            .unwrap_or_default();
        let empty = Map::new();
        let props = node
            .get("properties")
            .and_then(Value::as_object)
            .unwrap_or(&empty);
        let mut lines = String::new();
        for (key, prop) in props.iter() {
            let ty = self.render_type(prop, View::Read);
            let q = if required.contains(key.as_str()) {
                ""
            } else {
                "?"
            };
            lines.push_str(&format!("  {}{}: {};\n", ident(key), q, ty));
        }
        format!("export interface {name} {{\n{lines}}}\n\n")
    }

    /// A read-oriented converter for a realtime root: it injects the document id
    /// on read (so the read view's `id: string` holds) and strips that id field
    /// on write so it is never persisted into document data (the doc-id is the
    /// path, not a field). Write payloads should use the `{name}Write` type
    /// directly; this converter is a single read app-type because a read value
    /// (e.g. `Timestamp | null`) is not a write value (`FieldValue`).
    fn render_converter(&mut self, name: &str, node: &Value) -> String {
        self.used.insert("FirestoreDataConverter");
        let const_name = lower_first(name);
        let read = name;
        let (to_body, from_body) =
            match node.get("x-firestore-doc-id-field").and_then(Value::as_str) {
                Some(doc_id) => (
                    format!("    const {{ {doc_id}: _id, ...rest }} = model;\n    return rest;\n"),
                    format!(
                        "    const data = snapshot.data(options) as Omit<{read}, \"{doc_id}\">;\n    return {{ ...data, {doc_id}: snapshot.id }};\n",
                    ),
                ),
                None => (
                    "    return model;\n".to_string(),
                    format!("    return snapshot.data(options) as {read};\n"),
                ),
            };
        format!(
            "// Read converter (onSnapshot / getDoc): injects the doc id. For writes\n\
             // use `{read}Write` with setDoc/updateDoc directly (not via this converter).\n\
             export const {const_name}Converter: FirestoreDataConverter<{read}> = {{\n\
             \x20 toFirestore: (model) => {{\n\
             {to_body}\
             \x20 }},\n\
             \x20 fromFirestore: (snapshot, options) => {{\n\
             {from_body}\
             \x20 }},\n\
             }};\n\n"
        )
    }

    /// Optionality (`?`) is orthogonal to value-nullability.
    fn is_optional(&self, key: &str, prop: &Value, view: View, required: &BTreeSet<&str>) -> bool {
        match view {
            // write = "what must I provide to create a valid doc" = Pydantic required.
            View::Write => !required.contains(key),
            // read: required ONLY if presence is guaranteed across live docs.
            View::Read => read_optional(prop, required, key),
        }
    }

    fn render_type(&mut self, node: &Value, view: View) -> String {
        // 1) Firestore native types override the JSON shape.
        if let Some(fs) = node.get("x-firestore-type").and_then(Value::as_str) {
            return self.render_firestore(fs, node, view);
        }
        // 2) $ref -> named type (per-view name for objects).
        if let Some(r) = node.get("$ref").and_then(Value::as_str) {
            return self.render_ref(r, view);
        }
        // 3) const literal.
        if let Some(c) = node.get("const") {
            return literal(c);
        }
        // 4) inline enum. String enums read as an open union (trap #5).
        if let Some(arr) = node.get("enum").and_then(Value::as_array) {
            let all_string = arr.iter().all(Value::is_string);
            // Plain DTOs use strict inline enums (no open union).
            if self.plain {
                return arr.iter().map(literal).collect::<Vec<_>>().join(" | ");
            }
            // Compat signature: a string enum is read-equivalent to `string`;
            // numeric enums inline their members so member changes are visible.
            if self.compat {
                if all_string {
                    return "string".to_string();
                }
                return arr.iter().map(literal).collect::<Vec<_>>().join(" | ");
            }
            let strict = arr.iter().map(literal).collect::<Vec<_>>().join(" | ");
            if view == View::Read && all_string {
                return format!("{strict}{OPEN_ENUM_SUFFIX}");
            }
            return strict;
        }
        // 5) anyOf / oneOf -> union (null branch -> "null").
        for k in ["anyOf", "oneOf"] {
            if let Some(arr) = node.get(k).and_then(Value::as_array) {
                let parts: Vec<String> = arr.iter().map(|b| self.render_type(b, view)).collect();
                return self.union(parts);
            }
        }
        // 6) by JSON "type" (string or array of strings).
        match node.get("type") {
            Some(Value::String(t)) => self.render_json_type(t, node, view),
            Some(Value::Array(types)) => {
                let parts: Vec<String> = types
                    .iter()
                    .filter_map(Value::as_str)
                    .map(|t| self.render_json_type(t, node, view))
                    .collect();
                self.union(parts)
            }
            _ => "unknown".to_string(),
        }
    }

    /// Join union branches, deduplicated. In compat mode the branches are also
    /// sorted: a union is a set, so reordering its members is not a contract
    /// change (tuples, rendered with `[...]`, keep their order and are unaffected).
    fn union(&self, parts: Vec<String>) -> String {
        let mut seen = BTreeSet::new();
        let mut ordered = Vec::new();
        for p in parts {
            if seen.insert(p.clone()) {
                ordered.push(p);
            }
        }
        if self.compat {
            ordered.sort();
        }
        ordered.join(" | ")
    }

    fn render_firestore(&mut self, fs: &str, node: &Value, view: View) -> String {
        match fs {
            "timestamp" => {
                let server = node
                    .get("x-firestore-server-timestamp")
                    .and_then(Value::as_bool)
                    .unwrap_or(false);
                match (view, server) {
                    (View::Read, true) => {
                        self.used.insert("Timestamp");
                        "Timestamp | null".to_string()
                    }
                    (View::Read, false) => {
                        self.used.insert("Timestamp");
                        "Timestamp".to_string()
                    }
                    (View::Write, true) => {
                        self.used.insert("FieldValue");
                        "FieldValue".to_string()
                    }
                    (View::Write, false) => {
                        self.used.insert("Timestamp");
                        "Timestamp | Date".to_string()
                    }
                }
            }
            "bytes" => {
                // The firebase client SDK returns/accepts a `Bytes` wrapper for
                // blob fields (not a raw Uint8Array; use bytes.toUint8Array()).
                self.used.insert("Bytes");
                "Bytes".to_string()
            }
            "geopoint" => {
                self.used.insert("GeoPoint");
                "GeoPoint".to_string()
            }
            "vector" => {
                // Firestore vector field (vector search); client SDK `VectorValue`.
                self.used.insert("VectorValue");
                "VectorValue".to_string()
            }
            "reference" => {
                self.used.insert("DocumentReference");
                // a reference always points to the canonical (read) stored shape.
                match node.get("x-firestore-ref-target").and_then(Value::as_str) {
                    Some(t) => format!("DocumentReference<{}>", t),
                    None => {
                        self.used.insert("DocumentData");
                        "DocumentReference<DocumentData>".to_string()
                    }
                }
            }
            _ => "unknown".to_string(),
        }
    }

    fn render_ref(&mut self, r: &str, view: View) -> String {
        let name = r.rsplit('/').next().unwrap_or(r);
        // Shared types are imported from a sibling module, not defined here; the
        // referenced name still renders the same (the import provides it).
        if self.shared.contains(name) {
            self.shared_used.insert(name.to_string());
        }
        let def = self.defs.get(name);
        let is_enum = def.map(|d| d.get("enum").is_some()).unwrap_or(false);
        if is_enum {
            // The enum def is emitted once, view-agnostic (no Write suffix).
            // Openness (trap #5) is applied at the read reference site only,
            // and only for string enums (no clean open idiom for numbers).
            let string_enum = def.map(is_string_enum_node).unwrap_or(false);
            if self.plain {
                // Plain DTOs use strict enums (no open union).
                return name.to_string();
            }
            if self.compat {
                // Compat signature: string enum -> `string`; numeric enum inlines
                // its members so member changes surface as a signature change.
                if string_enum {
                    return "string".to_string();
                }
                if let Some(arr) = def.and_then(|d| d.get("enum")).and_then(Value::as_array) {
                    return arr.iter().map(literal).collect::<Vec<_>>().join(" | ");
                }
                return name.to_string();
            }
            if view == View::Read && string_enum {
                format!("{name}{OPEN_ENUM_SUFFIX}")
            } else {
                name.to_string()
            }
        } else {
            match view {
                View::Read => name.to_string(),
                View::Write => format!("{name}Write"),
            }
        }
    }

    fn render_json_type(&mut self, t: &str, node: &Value, view: View) -> String {
        match t {
            "string" => "string".to_string(),
            "integer" | "number" => "number".to_string(),
            "boolean" => "boolean".to_string(),
            "null" => "null".to_string(),
            "array" => {
                // 2020-12 fixed tuple: prefixItems -> [T1, T2, ...]
                if let Some(prefix) = node.get("prefixItems").and_then(Value::as_array) {
                    let parts: Vec<String> =
                        prefix.iter().map(|it| self.render_type(it, view)).collect();
                    return format!("[{}]", parts.join(", "));
                }
                if let Some(items) = node.get("items") {
                    let inner = self.render_type(items, view);
                    if inner.contains('|') {
                        format!("({inner})[]")
                    } else {
                        format!("{inner}[]")
                    }
                } else {
                    "unknown[]".to_string()
                }
            }
            "object" => {
                // dict[str, T] -> Record<string, T>
                match node.get("additionalProperties") {
                    Some(Value::Object(_)) => {
                        let inner =
                            self.render_type(node.get("additionalProperties").unwrap(), view);
                        format!("Record<string, {inner}>")
                    }
                    Some(Value::Bool(true)) | None => "Record<string, unknown>".to_string(),
                    _ => "Record<string, never>".to_string(),
                }
            }
            _ => "unknown".to_string(),
        }
    }
}

/// Read-side open-enum tail: lets a string union accept unknown members so a
/// backend adding/removing enum values never breaks an old front (trap #5).
const OPEN_ENUM_SUFFIX: &str = " | (string & {})";

/// Whether a field is optional in the read view: required ONLY when presence is
/// guaranteed across all live docs (`required` ∩ presence-guaranteed). Shared by
/// the emitter and the compat gate so the two never drift.
pub fn read_optional(prop: &Value, required: &BTreeSet<&str>, key: &str) -> bool {
    let guaranteed = prop
        .get("x-firestore-presence-guaranteed")
        .and_then(Value::as_bool)
        .unwrap_or(false);
    !(required.contains(key) && guaranteed)
}

/// The emit-mode TypeScript type of a single field in a given view (used by the
/// `gen-docs` support matrix so the documented types are derived from the real
/// emitter, never hand-maintained). `defs` resolves `$ref`s (may be empty).
pub fn field_type(defs: &Map<String, Value>, prop: &Value, view: View) -> String {
    let mut ctx = Ctx {
        defs,
        used: BTreeSet::new(),
        compat: false,
        plain: false,
        shared: BTreeSet::new(),
        shared_used: BTreeSet::new(),
    };
    ctx.render_type(prop, view)
}

/// The structural read-view signature of a single field, used by the compat gate.
/// `defs` is the bundle's `$defs` (needed to resolve `$ref` enums). String enums
/// collapse to `string` (open unions are read-equivalent to `string`), so the
/// surrounding structure (arrays, null branches) is what the gate compares.
pub fn read_type_signature(defs: &Map<String, Value>, prop: &Value) -> String {
    let mut ctx = Ctx {
        defs,
        used: BTreeSet::new(),
        compat: true,
        plain: false,
        shared: BTreeSet::new(),
        shared_used: BTreeSet::new(),
    };
    ctx.render_type(prop, View::Read)
}

/// A typed path builder from a collection template, e.g.
/// `rooms/{roomId}/messages` -> `export const messagesPath = (roomId: string) =>
/// \`rooms/${roomId}/messages\`;`. The const is named after the trailing
/// collection segment; each `{placeholder}` becomes a typed string argument.
fn render_path_helper(template: &str) -> String {
    let mut args: Vec<String> = Vec::new();
    let mut literal = String::new();
    for segment in template.split('/') {
        literal.push('/');
        if let Some(name) = segment.strip_prefix('{').and_then(|s| s.strip_suffix('}')) {
            args.push(format!("{name}: string"));
            literal.push_str(&format!("${{{name}}}"));
        } else {
            literal.push_str(segment);
        }
    }
    let literal = literal.trim_start_matches('/');
    let last = template
        .rsplit('/')
        .find(|s| !s.starts_with('{'))
        .unwrap_or("doc");
    let const_name = format!("{}Path", lower_first(last));
    format!(
        "export const {const_name} = ({}) => `{literal}`;\n\n",
        args.join(", ")
    )
}

/// Lowercase the first character (PascalCase type -> camelCase value name).
fn lower_first(name: &str) -> String {
    let mut chars = name.chars();
    match chars.next() {
        Some(c) => c.to_lowercase().chain(chars).collect(),
        None => String::new(),
    }
}

/// True when the node is an enum whose every member is a string literal.
fn is_string_enum_node(node: &Value) -> bool {
    node.get("enum")
        .and_then(Value::as_array)
        .map(|a| !a.is_empty() && a.iter().all(Value::is_string))
        .unwrap_or(false)
}

fn literal(v: &Value) -> String {
    match v {
        Value::String(s) => format!("\"{}\"", s.replace('"', "\\\"")),
        Value::Bool(b) => b.to_string(),
        Value::Number(n) => n.to_string(),
        Value::Null => "null".to_string(),
        _ => "unknown".to_string(),
    }
}

fn ident(key: &str) -> String {
    let valid = !key.is_empty()
        && key
            .chars()
            .next()
            .map(|c| c.is_ascii_alphabetic() || c == '_' || c == '$')
            .unwrap_or(false)
        && key
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$');
    if valid {
        key.to_string()
    } else {
        format!("\"{}\"", key.replace('"', "\\\""))
    }
}

/// PyO3 bindings (compiled only for the maturin extension build). Lets the
/// Python layer call the emitter natively instead of shelling out to the binary.
#[cfg(feature = "python")]
mod python {
    use pyo3::exceptions::PyValueError;
    use pyo3::prelude::*;

    /// Emit read/write TypeScript from a contract bundle given as a JSON string.
    #[pyfunction]
    fn emit(bundle_json: &str) -> PyResult<String> {
        let bundle: serde_json::Value =
            serde_json::from_str(bundle_json).map_err(|e| PyValueError::new_err(e.to_string()))?;
        Ok(crate::emit(&bundle))
    }

    /// Like `emit`, but `shared_names` are imported from `shared_path` (a TS module
    /// specifier relative to the output file) instead of being defined.
    #[pyfunction]
    fn emit_shared(
        bundle_json: &str,
        shared_path: &str,
        shared_names: Vec<String>,
    ) -> PyResult<String> {
        let bundle: serde_json::Value =
            serde_json::from_str(bundle_json).map_err(|e| PyValueError::new_err(e.to_string()))?;
        Ok(crate::emit_shared(&bundle, shared_path, &shared_names))
    }

    /// Emit plain (non-Firestore DTO) TypeScript from a standard JSON Schema bundle.
    #[pyfunction]
    fn emit_plain(bundle_json: &str) -> PyResult<String> {
        let bundle: serde_json::Value =
            serde_json::from_str(bundle_json).map_err(|e| PyValueError::new_err(e.to_string()))?;
        Ok(crate::emit_plain(&bundle))
    }

    /// Diff two contract bundles (JSON strings). Returns a JSON array of findings:
    /// `[{"def", "field"|null, "verdict": "SAFE"|"BREAKING", "message"}]`.
    #[pyfunction]
    fn compat(old_json: &str, new_json: &str) -> PyResult<String> {
        use crate::compat::{diff, Verdict};
        let old: serde_json::Value =
            serde_json::from_str(old_json).map_err(|e| PyValueError::new_err(e.to_string()))?;
        let new: serde_json::Value =
            serde_json::from_str(new_json).map_err(|e| PyValueError::new_err(e.to_string()))?;
        let findings: Vec<serde_json::Value> = diff(&old, &new)
            .iter()
            .map(|f| {
                serde_json::json!({
                    "def": f.def,
                    "field": f.field,
                    "verdict": match f.verdict {
                        Verdict::Safe => "SAFE",
                        Verdict::Breaking => "BREAKING",
                    },
                    "message": f.message,
                })
            })
            .collect();
        Ok(serde_json::Value::Array(findings).to_string())
    }

    #[pymodule]
    fn _core(m: &Bound<'_, PyModule>) -> PyResult<()> {
        m.add_function(wrap_pyfunction!(emit, m)?)?;
        m.add_function(wrap_pyfunction!(emit_plain, m)?)?;
        m.add_function(wrap_pyfunction!(emit_shared, m)?)?;
        m.add_function(wrap_pyfunction!(compat, m)?)?;
        Ok(())
    }
}
