use firepact_core::compat::{diff, is_breaking, Finding};
use firepact_core::{emit, emit_plain, emit_shared, field_type, View};
use serde_json::{json, Value};
use std::io::Read;
use std::path::PathBuf;
use std::process::exit;

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let code = match args.first().map(String::as_str) {
        Some("emit") => cmd_emit(&args[1..]),
        Some("compat") => cmd_compat(&args[1..]),
        Some("gen-docs") => cmd_gen_docs(),
        Some(other) => {
            eprintln!("firepact: unknown subcommand '{other}'");
            usage();
            2
        }
        None => {
            usage();
            2
        }
    };
    exit(code);
}

fn usage() {
    eprintln!("usage:");
    eprintln!("  firepact emit [<bundle.json>|-]            # bundle from file or stdin");
    eprintln!("  firepact compat <old.json> <new.json>");
    eprintln!("  firepact compat --history <dir> --new <file>");
    eprintln!("  firepact gen-docs                          # Firestore support matrix (markdown)");
}

/// `gen-docs`: emit a Firestore field-type support matrix as markdown. The
/// read/write columns are derived by running the emitter on a sample field per
/// type, so the document can never drift from the actual emitter.
fn cmd_gen_docs() -> i32 {
    // (Firestore type, Python annotation, sample field schema). Samples are
    // self-contained ($ref names need no def to render their name/Write form).
    let rows: [(&str, &str, Value); 14] = [
        ("String", "`str`", json!({"type": "string"})),
        ("Number", "`int` / `float`", json!({"type": "integer"})),
        ("Boolean", "`bool`", json!({"type": "boolean"})),
        (
            "Null",
            "`T | None`",
            json!({"anyOf": [{"type": "string"}, {"type": "null"}]}),
        ),
        (
            "Map",
            "`dict[str, T]`",
            json!({"type": "object", "additionalProperties": {"type": "string"}}),
        ),
        (
            "Array",
            "`list[T]`",
            json!({"type": "array", "items": {"type": "string"}}),
        ),
        (
            "Array (tuple)",
            "`tuple[A, B]`",
            json!({"type": "array", "prefixItems": [{"type": "integer"}, {"type": "string"}]}),
        ),
        (
            "Timestamp (server)",
            "`Annotated[datetime, FirestoreServerTimestamp()]`",
            json!({"type": "string", "x-firestore-type": "timestamp", "x-firestore-server-timestamp": true}),
        ),
        (
            "Timestamp (plain)",
            "`datetime`",
            json!({"type": "string", "x-firestore-type": "timestamp"}),
        ),
        (
            "GeoPoint",
            "`Annotated[..., FirestoreGeoPoint()]`",
            json!({"x-firestore-type": "geopoint"}),
        ),
        (
            "Bytes",
            "`bytes`",
            json!({"type": "string", "x-firestore-type": "bytes"}),
        ),
        (
            "Reference",
            "`Annotated[str, FirestoreRef(\"X\")]`",
            json!({"type": "string", "x-firestore-type": "reference", "x-firestore-ref-target": "X"}),
        ),
        (
            "Vector",
            "`Annotated[list[float], FirestoreVector()]`",
            json!({"type": "array", "items": {"type": "number"}, "x-firestore-type": "vector"}),
        ),
        (
            "Enum (string)",
            "`StrEnum` / `Literal`",
            json!({"type": "string", "enum": ["a", "b"]}),
        ),
    ];

    let empty = serde_json::Map::new();
    let mut out = String::new();
    out.push_str("# Firestore field-type support\n\n");
    out.push_str(
        "<!-- AUTO-GENERATED by `firepact gen-docs` (just gen-docs). DO NOT EDIT. -->\n\n",
    );
    out.push_str(
        "Every Firestore field value type firepact maps, with the read and write\n\
         view TypeScript derived from the actual emitter. See [contract.md](contract.md)\n\
         for the projection rules and [adr/](adr/) for the decisions.\n\n",
    );
    out.push_str("| Firestore type | Python | read view | write view |\n");
    out.push_str("|---|---|---|---|\n");
    for (fs, py, field) in &rows {
        // Escape `|` so unions (e.g. `string | null`) don't break the table cell.
        let py = py.replace('|', "\\|");
        let read = field_type(&empty, field, View::Read).replace('|', "\\|");
        let write = field_type(&empty, field, View::Write).replace('|', "\\|");
        out.push_str(&format!("| {fs} | {py} | `{read}` | `{write}` |\n"));
    }
    out.push_str(
        "\nRealtime roots additionally get `{Name}` / `{Name}Write` / \
         `{Name}Update = UpdateData<{Name}Write>`, a read converter \
         (`{name}Converter`, injects `snapshot.id`), and a typed path helper.\n",
    );
    print!("{out}");
    0
}

/// Read the bundle from `path`, or from stdin when the arg is `-` or absent.
fn read_input(arg: Option<&String>) -> Result<String, String> {
    match arg.map(String::as_str) {
        None | Some("-") => {
            let mut buf = String::new();
            std::io::stdin()
                .read_to_string(&mut buf)
                .map_err(|e| format!("read stdin: {e}"))?;
            Ok(buf)
        }
        Some(path) => std::fs::read_to_string(path).map_err(|e| format!("read {path}: {e}")),
    }
}

fn cmd_emit(args: &[String]) -> i32 {
    let plain = args.iter().any(|a| a == "--plain");
    let shared = flag(args, "--shared");
    let shared_names: Vec<String> = flag(args, "--shared-names")
        .unwrap_or_default()
        .split(',')
        .filter(|s| !s.is_empty())
        .map(str::to_string)
        .collect();
    // The input path/`-` is the first positional, skipping flags and the values
    // of value-flags (--shared / --shared-names).
    let input_arg = {
        let mut found = None;
        let mut skip_next = false;
        for a in args {
            if skip_next {
                skip_next = false;
                continue;
            }
            match a.as_str() {
                "--shared" | "--shared-names" => skip_next = true,
                "-" => {
                    found = Some(a);
                    break;
                }
                s if !s.starts_with('-') => {
                    found = Some(a);
                    break;
                }
                _ => {}
            }
        }
        found
    };
    let raw = match read_input(input_arg) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("{e}");
            return 1;
        }
    };
    let bundle: serde_json::Value = match serde_json::from_str(&raw) {
        Ok(v) => v,
        Err(e) => {
            eprintln!("parse: {e}");
            return 1;
        }
    };
    let out = match (plain, shared) {
        (true, _) => emit_plain(&bundle),
        (false, Some(path)) => emit_shared(&bundle, &path, &shared_names),
        (false, None) => emit(&bundle),
    };
    print!("{out}");
    0
}

fn load_json(path: &str) -> Result<serde_json::Value, String> {
    let raw = std::fs::read_to_string(path).map_err(|e| format!("read {path}: {e}"))?;
    serde_json::from_str(&raw).map_err(|e| format!("parse {path}: {e}"))
}

/// All `*.json` files in `dir`, sorted by name (deterministic order).
fn history_files(dir: &str) -> Result<Vec<PathBuf>, String> {
    let mut files: Vec<PathBuf> = std::fs::read_dir(dir)
        .map_err(|e| format!("read dir {dir}: {e}"))?
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| p.extension().and_then(|s| s.to_str()) == Some("json"))
        .collect();
    files.sort();
    Ok(files)
}

fn report(label: &str, findings: &[Finding]) {
    for f in findings {
        eprintln!("[{label}] {}", f.report_line());
    }
}

fn cmd_compat(args: &[String]) -> i32 {
    // Form A: compat <old.json> <new.json>
    // Form B: compat --history <dir> --new <file>   (FULL_TRANSITIVE)
    if let (Some(dir), Some(new_path)) = (flag(args, "--history"), flag(args, "--new")) {
        return cmd_compat_history(&dir, &new_path);
    }
    let positionals: Vec<&String> = args.iter().filter(|a| !a.starts_with("--")).collect();
    if positionals.len() != 2 {
        eprintln!("compat: expected <old.json> <new.json> or --history <dir> --new <file>");
        return 2;
    }
    let (old, new) = match (load_json(positionals[0]), load_json(positionals[1])) {
        (Ok(o), Ok(n)) => (o, n),
        (Err(e), _) | (_, Err(e)) => {
            eprintln!("{e}");
            return 1;
        }
    };
    let findings = diff(&old, &new);
    report("compat", &findings);
    if is_breaking(&findings) {
        eprintln!("compat: BREAKING changes detected");
        1
    } else {
        eprintln!("compat: compatible");
        0
    }
}

/// FULL_TRANSITIVE: diff the new bundle against every past version. Any version
/// it would break is a failure (any generation of doc may still be live).
fn cmd_compat_history(dir: &str, new_path: &str) -> i32 {
    let new = match load_json(new_path) {
        Ok(v) => v,
        Err(e) => {
            eprintln!("{e}");
            return 1;
        }
    };
    let files = match history_files(dir) {
        Ok(f) => f,
        Err(e) => {
            eprintln!("{e}");
            return 1;
        }
    };
    // If --new lives inside the history dir, don't diff it against itself
    // (an identity diff is always SAFE and would mask missing history).
    let new_canon = std::fs::canonicalize(new_path).ok();
    let mut any_breaking = false;
    let mut compared = 0usize;
    for past in &files {
        if new_canon.is_some() && std::fs::canonicalize(past).ok() == new_canon {
            continue;
        }
        compared += 1;
        let label = past
            .file_name()
            .and_then(|s| s.to_str())
            .unwrap_or("<version>");
        let past_bundle = match load_json(&past.to_string_lossy()) {
            Ok(v) => v,
            Err(e) => {
                eprintln!("{e}");
                return 1;
            }
        };
        let findings = diff(&past_bundle, &new);
        report(label, &findings);
        any_breaking |= is_breaking(&findings);
    }
    if any_breaking {
        eprintln!("compat: BREAKING against at least one past version");
        1
    } else {
        eprintln!("compat: compatible with all {compared} past version(s)");
        0
    }
}

/// Value following `name` in the argument list, if present. A following token
/// that is itself a flag (`--x`) is treated as a missing value, not the value.
fn flag(args: &[String], name: &str) -> Option<String> {
    let idx = args.iter().position(|a| a == name)?;
    args.get(idx + 1).filter(|v| !v.starts_with("--")).cloned()
}
